### ISSUE TITLE
import lycon2

### ISSUE THREAD

**Issue by benblack769** [PettingZoo-Team/lycon2#1]
On installing lycon2, you should be able to do

```
import lycon2
```

Instead of 

```
import lycon
```

I belive all that needs to be done is to rename the `lycon` folder in the root directory of the project, and change imports within the project, but there might be some more work here.

**Comment by ahmed-akader** [comment]
See e889c6bd0e2428323fc237aa654e4b2346f71c42 and 0588c69c8dbad1d430bc9a52f71c1c17042dd147. I left the C files unchanged for the most part.
