### ISSUE TITLE
Upon pip installing and import, I can't import

### ISSUE THREAD

**Issue by benblack769** [PettingZoo-Team/lycon2#5]
```
$ pip install lycon2
$ python -c "import lycon"
Illegal instruction (core dumped)
```

What illegal instruction is this? Perhaps `objdump` and assembly inspection can help?

Probably an issue with what compiler environment is on the manylinux docker. The `LYCON_SSE2`, `LYCON_NEON` flags, etc should probably be set in the CI build, not autodiscovered by the compiler (in a source build, they should still be autodiscovered).

**Comment by ahmed-akader** [comment]
Seems to work fine for a conda env with `python=3.6` on Ubuntu. I suspect this has something to do with the way the build script iterates over python versions. In relation to that, and as the python version on the worker didn't seem relevant, it seemed sufficient to build all target versions on a single worker. Now I'm not sure about that.

@benblack769 Are you aware of better ways to set up this Linux build script?

**Comment by benblack769** [comment]
I am running python==3.6.9 on ubuntu. Also, the python version in CI should be irrelevant, as the docker file installs its own versions of python. I went ahead and ran gdb to find the illegal instruction, and I got 

```
0x00007ffff6526ba5 in lycon::JpegEncoder::JpegEncoder() ()
   from /home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/_lycon.so
(gdb) bt
#0  0x00007ffff6526ba5 in lycon::JpegEncoder::JpegEncoder() ()
   from /home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/_lycon.so
#1  0x00007ffff6525358 in lycon::ImageCodecInitializer::ImageCodecInitializer() ()
   from /home/ben/.virtualenvs/main_env/lib/python3.6/site-packages/_lycon.so
...
```

**Comment by benblack769** [comment]
Yeah, I ran a source build of lycon2 and there is no problem, only on a wheel install.

**Comment by benblack769** [comment]
Seems to work as of lycon2==0.3.1
